spring:
  application:
    name: hello-search-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(HdT9qJmmVEkPQ91sXXzMPRlV7TbZwFXHhgyU5WA8OCHOkwZ3QNAEZKUhA0iqkZUzdPbRQd0fh7UHgC6Pa766Ew4IYInSNLrzRJVAh6PzKPU=)
    username: root
    password: ENC(niQlo3uQx8ZkV3MAqB709P2acAi1Zpc1xP00OnbOMA6qUvKoynjiZ6l0o29NaYU/)
  elasticsearch:
    uris: ENC(L+gqD7a5qEnchYRNi0ZH4fiQqNWKhx4iZ1DOibrRgO8Qx+dmpuOvwpI2hEL6mUoRnP854BKyEpN6BxtIpeInaA==)
    username: elastic
    password: changeme
    connection-timeout: 5s
    socket-timeout: 10s
    restclient:
      ssl:
        bundle: elasticsearch
  ssl:
    bundle:
      jks:
        elasticsearch:
          key:
            alias: elasticsearch-ca
          truststore:
            location: classpath:elasticsearch.jks
            password: ENC(Azbv/ZYiYzGILGxay0HssEJBghlKVKWCQ2oNYePZ0l2veOYNYulciPEwavFPem8O)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        id:
          new_generator_mappings: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      index:
        product: product_index

server:
  port: 9999

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace


jasypt:
  encryptor:
    bootstrap: true
    password: ${JASYPT_PASSWORD:test}